name = "receipt"
main = "src/index.ts"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2026-02-28"

[[ d1_databases ]]
binding = "DB"
database_name = "receipt"
database_id = "7194a31d-893e-46e9-9d04-48a294b33c81"
migrations_dir = "drizzle"
